### ISSUE TITLE
Doesn't shows the graph

### ISSUE THREAD

**Issue by nishantaMishra** [btjones-me/raman_spectroscopy#1]
I have cloned the repository and run the code. The code gets executed without errors but it doesn't show any graph. I have not edited anything, just trying to run your codes. I am running it on a Debian-based Linux.

**Comment by Gaurang105** [comment]
Firstly, In this sigma is set to 2, which is a scalar. This is incorrect unless your y data (y) consists of exactly one point.

Instead, sigma should be a 1-D sequence of the same length as y, and it should contain positive numbers representing the standard deviations of the errors in y.


Change it to like this:


sigma = [2] * len(y)
popt, pcov = curve_fit(func, x, y, p0=guess, maxfev=14000, sigma=sigma)

And then copy the whole code and run it in Jupyter Notebook.

**Comment by btjones-me** [comment]
Thanks @nishantaMishra - if you haven't solved this already, there could be a few things causing this.

I got ChatGPT to format my thoughts, here:

1) Backend Issue: Matplotlib uses a number of different backends to render plots. It's possible that the backend being used in this particular Debian-based Linux setup isn't correctly configured. This is often an issue with remote servers or headless machines that don't have an X server running. You could suggest trying different backends. The backend can be changed by adding the following lines to the top of the script:

```python
import matplotlib
matplotlib.use('agg') # or try 'TkAgg', 'Qt4Agg', 'GTK3Agg'
``` 

2) Displaying plots in a non-interactive script: If the code is not being run interactively (i.e., not in a Python shell or a Jupyter notebook), then plt.show() may not behave as expected. They should call plt.show() after all plotting commands. If there is no call to plt.show() at the end or if the script exits before plt.show() is called, no window will appear.

3) Missing GUI Framework: If they are trying to use a GUI-specific backend such as TkAgg, they might not have the required GUI framework installed. If they have used apt to install Python, it is sometimes missing the tk package. This can be installed with sudo apt-get install python3-tk.


Alternatively, if you still can't get it to visualise, you can save each plot individually like this: 
```python
plt.savefig('filename.png')  # replace 'filename.png' with the desired output file name
```

**Comment by nishantaMishra** [comment]
Thank you, Benjamin Jones ! There was indeed a problem with my python
configuration.




बुध, 21 जून 2023, 04:47 को Benjamin Jones ***@***.***> ने
लिखा:
